# aka-name

In [36]:
import pandas as pd
import numpy as np

In [38]:
aka_name = pd.read_csv('original/aka_name.csv', names=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], low_memory=False)

In [40]:
aka_name

,1,2,3,4,5,6,7,8,9,10
0,1,4061927,"Smith, Jessica Noel",NaN,S5325,J2542,S53,25c9d464e3ff2957533546aa92b397ed,NaN,NaN
1,2,4,"Short, Too",NaN,S63,T263,NaN,4e26116e5f9800cef90c8f8c38de2584,NaN,NaN
2,3,2701136,"Abdul-Hamid, Jaffar",NaN,A1345,J1613,NaN,fb5126fe9992e13156c636d726cec257,NaN,NaN
3,4,2701136,"Al-Hamid, Jaffar Abd",NaN,A4532,J1613,A453,179ad5f75c84c4bddd6733c66b6b0bb7,NaN,NaN
4,5,15,"Viera, Michael 'Power'",NaN,V6524,M2416,V6,354cea2b99f8b1f745ea6092eefa2bd7,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
901333,901339,1739545,JP,NaN,J1,NaN,NaN,24d22e03afb23edb45c6c8cfa16a280e,NaN,NaN
901334,901340,2701103,"Þórarinsdóttir, Lilja",NaN,R6523,L4265,NaN,a8452eebe9c8c2b50aec3e5a8b5cc626,NaN,NaN
901335,901341,1739575,Tommi,NaN,T5,NaN,NaN,56bb4a8d3f72d5a31aee0c317302dde5,NaN,NaN
901336,901342,1739578,"Hiller, Jaren",NaN,H4626,J6546,H46,bd0f3176e2d9520be530c66cd0918bc2,NaN,NaN
901337,901343,1598440,"Castilla, Raúl Vale",NaN,C2346,R4142,C234,0e5d34892724c9d28c3d1889029de7ad,NaN,NaN

In [42]:
wrong = aka_name[(~aka_name['9'].isnull()) | (~aka_name['10'].isnull())]
wrong

,1,2,3,4,5,6,7,8,9,10
25635,25636,67744,"Atkinson, Chaz 'We'll Sail Without 'em\"",,A325...","Chaz 'We'll sail without'em'""",NaN,A3252,C2424,NaN,e800dee690c6e81f71a3c2096d5832a4,NaN
59393,59395,151972,Boss\,"\""The""",NaN,B23,T12,B2,007c0cb0c120d69674aedc959f881a7a,NaN
90916,90918,233854,"\Cantinflas\""","Mario Moreno""",NaN,C5351,M6565,NaN,19f004360bd2f041dd2c0a01318ccc0b,NaN
112599,112601,280837,"\Jøden\""","Michael""",NaN,J3524,M2423,J35,98302f73aad9c3aacc3a3d84a94bd9fb,NaN
126723,126725,316470,"Corral, William 'Pete\"",,C6451,W4513,C64,91506...","José Luís""",NaN,A6252,J2426,A625,d57a39ac28ba35178e85c52d73ed3656,NaN
136756,136759,341975,"Dangio\"",,D52,,,53561f451ce33479cc82db90357978...","Lynn""",NaN,D5254,L5352,D525,21edd599755c19eb20a6e03e5d528b92,NaN
142519,142523,4078936,Beast\,"\""Bailey A.K.A. The""",NaN,B2314,B4231,B23,1c0d32916458c7c75d51f001d7b20656,NaN
144968,144972,3096692,Father\,"Clarence Day's \""Life with""",NaN,F3624,C4652,F36,e4d501852539f000859bdbdc0a3d928e,NaN
220218,220222,538021,"\Borolas\""","Joaquín García Vargas""",NaN,B6425,J2526,B642,6526774f1ce04414f56476409ce59060,NaN
220219,220223,538021,"\Borolas\""","Joaquín Garcías""",NaN,B6425,J2526,B642,16fdf7d68506db74c104549eee690470,NaN
220220,220224,538021,'Borolas\,"Joaquín García""",NaN,B6425,J2526,B642,d445ec6d95180c0da8bcd14ea75d97cf,NaN
234868,234872,573749,Titi\,"Agustín Gómez Marín \""El""",NaN,T3235,A2352,T3,0f217fb4f11713bdaf4066b3a376a43c,NaN
236220,236224,576956,'Piporro\,"Lalo Gonzalez""",NaN,P1642,L4252,P16,7a45fced475b4a71ea3017aabaf0e288,NaN
247496,247500,605081,Duco\,"Carlos Guarneros \""Don""",NaN,D2642,C6426,D2,ea1599f9d284a69db4bb3a0539dfde3d,NaN
294677,294681,727791,P.\,"Phillip Ivey \""Mr.""",NaN,P1415,P4156,P,6fa94e9cd572fbe7ae34cb7d7d593632,NaN
332174,332178,3465422,Kline\,"\""Stinkey""",NaN,K4523,S3524,K45,1497cc1a7eec69f20f8f963f552e8c25,NaN
368405,368409,906353,"\Frankenstein\""","Nathanael León""",NaN,F6525,N3545,NaN,76ec4e84ba2d867013316276134af773,NaN
375706,375710,922812,Deckhart\,"\""Aaron""",NaN,D2636,A6532,D263,75bd55df68c3312581419d083c50723d,NaN
407864,407868,3158297,Order\,"Team \""Law and""",NaN,O6363,T5453,O636,77bc41a33b78125a95ec3f69f97997d4,NaN
429716,429720,4114055,...\,"\""Positronic brains programmed by""",NaN,P2365,NaN,NaN,46bff7a06b0c1a62bd5cbb9ce3c08351,NaN
472764,472768,1160846,\Pico,"X. M. Olveira""",NaN,P2541,X5416,P2,e3eb7bfd0466f9982fed8cf4eebbc88f,NaN
474348,474352,1165104,Ormand\,"\""Benjamin""",NaN,O6531,B5256,O653,26890eb565f546715b6c48909269f654,NaN
478358,478362,1175745,"\Padillita\""","Gastón Padilla""",NaN,P3432,G2351,P343,3f2cd510b30464255efc21e74d48da9d,NaN
495901,495905,1219950,"\Apache\""","Daniel Peña""",NaN,A1235,D5412,A12,a3141f098369aaa4b7572f08b8150d2a,NaN
499063,499067,3179405,Order\,"Team \""Law and""",NaN,O6363,T5453,O636,77bc41a33b78125a95ec3f69f97997d4,NaN
518322,518326,1276298,Ramirez\,"Ignacio \""Nacho\""""",NaN,R5625,I2525,R562,5471c0dbb68b2fb334ff774c527ea7d2,NaN
531074,531078,1307480,Lou\,"Tommy Riggs and His \""Betty""",NaN,L3562,T5625,L,090876e9cd369f0aee21024bac140331,NaN
536059,536063,3922315,"[\Rocky\""]","Diorena B. Rock""",NaN,R2365,D6516,R2,2b34116d9af2f0f437b5f6c64d35deb1,NaN
561823,561827,1385238,"\Saza\""","Jose Sazatornil""",NaN,S2365,J2365,S2,7b7194a5db039c8dfa5575a132551233,NaN
597787,597791,1471354,Chicote\,"Armando Soto La Marina \""El""",NaN,C2365,A6532,C23,223e6dba69444b9f0eb78a5253136a39,NaN
610240,610244,4136493,"Strath, Spence 'Packy\"",,S3632,S1521,S363,7e45...","Spence 'Packy'""",NaN,S3632,S1521,S363,85143e9e912ecf47e73bbba6fda7e77e,NaN
617851,617856,2581535,Sytch\,"Tammy \""Sunny\""""",NaN,S3235,T5252,S32,a256ac48a4b439a6318676e3da452f8e,NaN
619100,619105,1522291,"\Tip\""","Luis Polack""",NaN,T1421,L2142,T1,38d26e63a57ebc6eb6ac0f4ef5d208c3,NaN
619292,619297,1522609,Bolas\,"Javier Sánchez \""El""",NaN,B4216,J1625,B42,c570b0b84e40672280a2d61e34829b5c,NaN
628760,628765,1546166,Goodridge\,"\""Liz""",NaN,G3632,L2363,NaN,2cf7638eadc4a3d3cbde7f79b1d615d8,NaN
633739,633743,4139259,Tipper\,"\""Mugsy""",NaN,T1652,M2316,T16,f4874e35e68d6d1afe401d0241608e03,NaN
647183,647188,4140878,"Ferenc, Utasi 'Junior\"",,F6523,U3256,F652,eb35...","Utasi 'Junior'""",NaN,F6523,U3256,F652,301f817a0503d803f47531b714e7602a,NaN
682698,682704,1684548,Youth\,"Tennessee Williams' \""Sweet Bird of""",NaN,Y3524,T5245,Y3,0b08752641ff2e763642b51408d9712e,NaN
692087,692093,2683076,"\X\""","Jen""",NaN,X25,J52,X,b7e7d19f490f36fb49408dd9090746e2,NaN
701251,701256,1728465,'Chiquilin\,"Gerardo Zepeda""",NaN,C2452,G6321,C245,d53e7c78f6668062255acaecdf29a311,NaN
714663,714669,81154,Crumpton\,"\""Jonathan Bailey""",NaN,C6513,J5351,NaN,fe4fcc4218f5d3573e3bf05b5e3c5276,NaN
779923,779929,2092459,"and SAbrina) Sa (from \MelisSA\""","\""ClarisSA\""""",NaN,A5321,NaN,NaN,858f1cba0a69eb92d21c7ff11463e287,NaN
803588,803593,859047,"\Texas\"" Terry",Iceman,"Ironman""",NaN,T2362,NaN,T236,d84b3e0998b3fe36d6df5791cbcc8fb7

In [44]:
wrong.shape[0]

43

In [47]:
correct = aka_name[(aka_name['9'].isnull()) & (aka_name['10'].isnull())]
print(correct.shape)
correct.to_csv('processed/aka_name.csv', index=False, header=False)

(901295, 10)

# aka_title

In [60]:
aka_title = pd.read_csv('original/aka_title.csv', names=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13'], low_memory=False)

In [62]:
wrong = aka_title[~aka_title['13'].isnull()]
wrong

,1,2,3,4,5,6,7,8,9,10,11,12,13
12898,4202,253725,"Mord in Pastell\"",,7,1975,M6351,4243,1,4,(West...","Presented by Fred Astaire""",NaN,2.0,1961,P6561,NaN,NaN,NaN,(USA) (alternative title),ba3e7bc23d0f91048d002ed4f04c2cc5
30167,11111,722134,"Krtek ve mìstì\"",,7,,K6321,11110,1,26,(Czechos...","au temps des croisades""",NaN,3.0,2003,A3512,NaN,NaN,NaN,(France) (long title),c13e574a7d0a707ef4de982295488430

In [64]:
correct = aka_title[aka_title['13'].isnull()]
print(correct.shape)
correct.to_csv('processed/aka_title.csv', index=False, header=False)

(361377, 13)

# cast_info

In [79]:
cast_info = pd.read_csv('original/cast_info.csv', names=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23'], low_memory=False)

ParserError: Error tokenizing data. C error: out of memory

# char_name

In [90]:
char_name = pd.read_csv('original/char_name.csv', names=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14'], low_memory=False)

In [94]:
wrong = char_name[(~char_name['8'].isnull()) | (~char_name['9'].isnull()) | (~char_name['10'].isnull()) | (~char_name['11'].isnull()) | (~char_name['12'].isnull()) | (~char_name['13'].isnull()) | (~char_name['14'].isnull())]
wrong

,1,2,3,4,5,6,7,8,9,10,11,12,13,14
134030,177736,"King \"",,,K52,,aef1fd60f1dadc70f2889b3787d7178...","amigo de Mateo""",NaN,NaN,R2635,M3,fb20d1a753fa67deabd187b200acde05,NaN,NaN,NaN,NaN,NaN,NaN
148862,122272,"Timo, \Timppa\""","medic""",NaN,NaN,T5351,M32,103c02d231a9ac2a81e3eb481a2ae20e,NaN,NaN,NaN,NaN,NaN,NaN
157715,128272,\Uh,"in episode...\""""",NaN,NaN,U5123,E123,d8228178cb86253a961b53e2deb69960,NaN,NaN,NaN,NaN,NaN,NaN
192166,128346,\She'll want socks,"too!\""""",NaN,NaN,S4532,T,e9e8c2865a112a9cb6b0ee13091b1880,NaN,NaN,NaN,NaN,NaN,NaN
209523,210733,"Bobby \Aces\""","Theater Actor""",NaN,NaN,B1236,A236,208b2f8f47faf759af94e86df51680f5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3071840,3063065,Herself - Presenter: Best Song nominees \Into ...,"\""The Scarlet Tide\""","\""You Will Be My Ain' True Love\""""",NaN,NaN,H6241,L1,2509ae74e951b9226e734869b6053649,NaN,NaN,NaN,NaN,NaN
3084063,3027303,Mrs. Jenkins - segment \There's This Travellin...,"See\""""",NaN,NaN,M6252,S,e7a8ebe5dff25e76b80c4372b3423a3d,NaN,NaN,NaN,NaN,NaN,NaN
3092861,3051737,"Kahn \Connie\"" Souphanousinphone","Jr.""",NaN,NaN,K5252,J6,cd89ca7c8abdbca3128ad679bc0df393,NaN,NaN,NaN,NaN,NaN,NaN
3128259,3104246,"Brmaid in \Baltyk\""","Zaba's lover""",NaN,NaN,B6535,L16,60c56a1607942cca96e3ffefd0995c2d,NaN,NaN,NaN,NaN,NaN,NaN
3136454,3103429,Interviewee \Boom to Bust,"1920-1929\"")""",NaN,NaN,I5361,NaN,f97f6e1e11fe960e553cc2bfa63a6f54,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
condition = (~char_name['8'].isnull()) | (~char_name['9'].isnull()) | (~char_name['10'].isnull()) | (~char_name['11'].isnull()) | (~char_name['12'].isnull()) | (~char_name['13'].isnull()) | (~char_name['14'].isnull())

correct = char_name[~condition]
print(correct.shape)
correct.to_csv('processed/char_name.csv', index=False, header=False)

(3139686, 14)

# company_name

In [105]:
company_name = pd.read_csv('original/company_name.csv', names=['1', '2', '3', '4', '5', '6', '7', '8'], low_memory=False)

In [107]:
wrong = company_name[(~company_name['8'].isnull())]
wrong

,1,2,3,4,5,6,7,8
34412,60985,"Studio \Orlenok\""","Central Television USSR""",[ru],NaN,S3645,S3645,909356683cb8bb5f9872a7f34242b81f
94078,82924,\I,"of the Craft...\""""",[us],NaN,I1326,I1326,3e798b706075164fb6b21cbf20e472d2
161202,130274,"Producentska grupa \Most\""","Zagreb""",NaN,NaN,P6325,NaN,1e9cf3da625add311321a8cab69458df

In [109]:
condition = (~company_name['8'].isnull())

correct = company_name[~condition]
print(correct.shape)
correct.to_csv('processed/company_name.csv', index=False, header=False)

(234994, 8)

# movie_companies

In [141]:
movie_companies = pd.read_csv('original/movie_companies.csv', names=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'], low_memory=False)

In [143]:
condition = (~movie_companies['6'].isnull()) | (~movie_companies['7'].isnull()) | (~movie_companies['8'].isnull()) | (~movie_companies['9'].isnull()) | (~movie_companies['10'].isnull()) | (~movie_companies['11'].isnull())

In [144]:
wrong = movie_companies[condition]
wrong

,1,2,3,4,5,6,7,8,9,10,11
13839,13840,53164,1372,1,(2003) (USA) (DVD) (episode \The Sorceror's Ap...,"1962)""",NaN,NaN,NaN,NaN,NaN
13892,13893,53192,1376,1,(1986) (USA) (VHS) (included in \The Best Of A...,"Vol. One\"")""",NaN,NaN,NaN,NaN,NaN
13985,13986,53250,1376,1,(1986) (USA) (VHS) (included in \The Best of A...,"Vol. One\"")""",NaN,NaN,NaN,NaN,NaN
14119,14120,53332,1376,1,(1986) (USA) (VHS) (included in \Best of Alfre...,"Vol. One\"")""",NaN,NaN,NaN,NaN,NaN
63555,63556,251030,3858,1,(2002) (UK) (DVD) (episode \Pirate Seagull,"The\"")""",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2512887,2512888,2423955,223298,2,"(videos \My Favorite Mistake\""","\""Everyday Is a Winding Road\"" and \""Home\"")""",NaN,NaN,NaN,NaN,NaN
2516983,2516984,2428184,113278,2,"(segments \Like a Rolling Stone\""","\""Army of Me\""","\""Hyperballad\"" and \""Everlong\"")""",NaN,NaN,NaN,NaN
2544308,2544309,2458214,161822,2,"(segments \Pride\""","\""The Unforgettable Fire\"" and \""When Love Co...",NaN,NaN,NaN,NaN,NaN
2544310,2544311,2458214,120583,2,"(segments \Pride\""","\""New Year's Day\"" and \""The Unforgettable Fi...",NaN,NaN,NaN,NaN,NaN
2544313,2544314,2458215,116866,2,"(segments \One\""","\""Miss Sarajevo\""","\""Hold Me",Thrill Me,Kiss Me,"Kill Me\"" \""The Fly\"" and \""Who's Gonna Ride ...",")"""

In [147]:
correct = movie_companies[~condition]
print(correct.shape)
correct.to_csv('processed/movie_companies.csv', index=False, header=False)

(2608836, 11)

# movie_info

In [163]:
movie_info = pd.read_csv('original/movie_info.csv', names=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21'], low_memory=False)

ParserError: Error tokenizing data. C error: Expected 21 fields in line 7445451, saw 63

# name

In [168]:
name = pd.read_csv('original/name.csv', names=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], low_memory=False)

In [172]:
condition = (~name['10'].isnull())

wrong = name[condition]
wrong

,1,2,3,4,5,6,7,8,9,10
351729,354028,Dash\Bridges,"Mell \""Marvel""",NaN,NaN,m,D2163,M4561,NaN,e341bcb791170c0f14e315547ff41425
1740546,1739580,"\Steff\""","Stefanie Oxmann Mcgaha""",NaN,NaN,f,S3123,S3152,S31,6d65f0b180a1560b74edf3d79cf7b9b4
3802789,3802843,Le\,"Bui Boi-Le \""Bebe""",NaN,NaN,NaN,L141,B1414,L,65890d3d4bdc2c943df9744308d3b124
4063076,4061927,"\J.Smith\""","Jessica Smith""",NaN,NaN,NaN,J2532,NaN,J253,eb80c6c403e34b2e59355ae65c61ab1d
4147890,4147861,"\Ghost\""","Matthew Clark""",NaN,NaN,NaN,G2353,M3246,G23,fb85de2bda63f39f4bdeef7f30ff08e1

In [174]:
correct = name[~condition]
print(correct.shape)
correct.to_csv('processed/name.csv', index=False, header=False)

(4167486, 10)

# person_info

In [209]:
names = [str(i) for i in range(1, 632)]
person_info = pd.read_csv('original/person_info.csv', names=names, low_memory=False)

ParserError: Error tokenizing data. C error: out of memory

# title

In [218]:
names = [str(i) for i in range(1, 15)]
title = pd.read_csv('original/title.csv', names=names, low_memory=False)

In [220]:
condition = (~title['13'].isnull()) | (~title['14'].isnull())

wrong = title[condition]
wrong

,1,2,3,4,5,6,7,8,9,10,11,12,13,14
9140,124832,"Zehut Sh'ula\"",,7,1997,,Z324,124831,1,3,,3ecbb...",Danny Pardo,"and Breanne Silvi""",NaN,7.0,2009,NaN,A2362,39009.0,1,44,NaN,897b95d7527f3ddd19f8c407effd2de6
57005,80501,"Co-Host Andy Cohen; \Steel Magnolias\"" Cast: Q...",Alfre Woodard,"Jill Scott""",NaN,7.0,2012,NaN,C2353,80464.0,2,26,NaN,4ec914112555c0fb2180cc7cab41c671
139420,102972,"Jamie's POV (Italian Job style)\"",,7,,,J5213,1...","Part 1""",NaN,7.0,1997.0,NaN,C5213,137695,2.0,2,NaN,ed3bb87170147bfddb2632e9c32d34cf,NaN
227793,240828,"You're the One That I Want\"",,7,2012,,Y6353,24...","o Ciumento e o Ciúme""",NaN,7.0,2008.0,NaN,C5325,211062,1.0,34,NaN,4ebf1f070023507c133701c1b5006ce9,NaN
259365,254886,"Which Way Are They Going?\"",,7,2012,,W2632,254...","Ma""",NaN,7.0,1951.0,NaN,I4162,278266,1.0,7,NaN,04fdb8c34e73c41f3dc82679de28256f,NaN
279903,260768,"The Girl Who Said, \It's Not You","It's Me\"" & Actually Meant It""",NaN,7.0,2012.0,NaN,G6423,260468,2.0,98,NaN,dedddbedcb23187cc41e6805f4ebfe22,NaN
331053,374165,"Las raíces delodio\"",,7,2001,,R2343,374006,,,,...","yami no noro no himitsu""",NaN,7.0,2002.0,NaN,A2565,384042,1.0,44,NaN,737bc876546c6087fc15bbfd2a95dbd4,NaN
402763,499983,"Debt Limit Deal: The House Says \Yes!\"" The Se...","\""No!\"" Can Anybody Cut","Cap and Balance DC?""",NaN,7.0,2011,NaN,D1345,499948.0,NaN,NaN,NaN,a9a7bc7881f846666ff9857f3c850fc3
533162,528524,"GJ senjô no kyoro\"",,7,2013,,G2525,528521,1,3,...","the Midfielder""",NaN,7.0,2008.0,NaN,R2353,508128,2.0,22,NaN,d5cf791a3c34fd2a97f31f960d6cd6a9,NaN
577828,570494,"Burning Spirits / Ghosts of the West\"",,7,2011...","Amazon Style""",NaN,7.0,1999.0,NaN,L1525,579356,6.0,2,NaN,5bb54d3a7a1a2b6463d015317c71b36e,NaN
595978,524182,"Mark Nesbitts 'Ghost of Gettysburg Home\"",,7,2...","Hang on to Your Friend's Life!""",NaN,7.0,1987.0,NaN,R2521,591915,1.0,24,NaN,bcf4e54af2aadf8bb4996f217c257f37,NaN
809278,853056,"Imoto, Imoto, Imoto da!\"",,7,2012,,I5353,85305...",Camera,"Cosmo""",NaN,7.0,2013,NaN,L2325,842128.0,2,6,NaN,a70cbfc0c9a887deb7c18acb5bd0fd9a
823360,873531,"Cariño, ¿cómo te gustan los huevos?\"",,7,2012,...","Please""",NaN,7.0,1950.0,NaN,G3523,819321,1.0,8,NaN,c4f5d1bef8142d0fb1458116b25a1e7a,NaN
1146240,1150848,Panda-kun no deshiiri/Dôbutsu darake no undôka...,"Bland Bathroom""",NaN,7.0,2008.0,NaN,B2145,1125572,5.0,12,NaN,a6e44428fa8a8a8c7c9e983e654825b9,NaN
1385551,1378228,"Living the \A List\"" Life! Affordable Luxury i...","Fashion & Food""",NaN,7.0,2011.0,NaN,L1523,1378101,NaN,NaN,NaN,055db0e3c410a4d8f500d813cb41715e,NaN
1490091,1449441,"Electricity According to John\"",,7,2008,,E4236...",Colin Ford,"Hunter Parrish and Godspell""",NaN,7.0,2011,NaN,E4152,1412026.0,1,34,NaN,9dc774a19818393830d459993547ec25
1521028,1501418,"Raiders of the Lost Crock of */@?#!\"",,7,2007,...","a Girl and a Mother's Day""",NaN,7.0,1999.0,NaN,T2645,1512167,2.0,20,NaN,8e589236d3dc10f833353f290b49dc22,NaN

In [222]:
correct = title[~condition]
print(correct.shape)
correct.to_csv('processed/title.csv', index=False, header=False)

(2527952, 14)